<?php


namespace App\Http\Resources\Json;

class JsonResource extends \Illuminate\Http\Resources\Json\JsonResource
{
    protected static bool $_IS_COLLECTION = false;

    public static function make(...$parameters)
    {
        self::$_IS_COLLECTION = false;
        return parent::make(...$parameters); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $resource
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public static function collection($resource)
    {
        self::$_IS_COLLECTION = true;
        return parent::collection($resource);
    }

}
