<?php


namespace App\Http\Resources\Json;

class JsonResource extends \Illuminate\Http\Resources\Json\JsonResource
{
    protected static bool $_IS_COLLECTION = false;

    protected $hiddenFields = [];

    public static function make(...$parameters)
    {
        self::$_IS_COLLECTION = false;
        return parent::make(...$parameters); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $resource
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public static function collection($resource)
    {
        self::$_IS_COLLECTION = true;
        return parent::collection($resource);
    }

    public function hide(array $fields)
    {
        $this->hiddenFields = $fields;
        return $this;
    }

    protected function filterFields($array)
    {
        return collect($array)->forget($this->hiddenFields)->toArray();
    }

    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }

}
